const STUDENTI = [
['Thinh',	'Bubbio'],
['Alonso',	'Carrillo'],
['enrico',	'ferro'],
['Marco',	'Popolo'],
['Joel',	'Stoppa'],
['Martina',	'Varaldo'],
['Matteo',	'Banchio'],
['Dario',	'Cognome'],
['Patrick',	'Casale'],
['Giorgio',	'Sechi'],
['Lorenzo',	'Coviello'],
['alessandro',	'zanchettin'],
['gabriele',	'moni'],
['Jonathan',	'Querio'],
['Matteo',	'Meringolo'],
['Edoardo',	'Gagliasso'],
['lorenzo',	'spilberga'],
['Luca',	'Pedrini'],
['Ernesto',	'Bianco'],
['Enrico',	'Floridia'],
['Marco',	'Calì'],
['francesco',	'falzetta'],
['Mattia',	'Brondino'],
['Luca',	'Pergola'],
['alessandro',	'cojocariu'],
['Lansana',	'Camara']
]